spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://host.docker.internal:8888
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/users,/users/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

    loadbalancer:
      health-check:
        enabled: true
      retry:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
